version: '3.9'

services:
  refine-app:
    container_name: pt-admin
    image: '${CI_DEPLOY_IMAGE}'
    restart: unless-stopped
    env_file: .env
    ports:
      - "5173:80"
    tty: true
    stdin_open: true