name: refine-admin
on:
  push:
    branches:
      - develop
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check version
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.CI_DEPLOY_IMAGE }}        

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
     CI_DEPLOY_IMAGE: ${{ vars.CI_DEPLOY_IMAGE }}
     CI_PRIVATE_KEY: ${{ secrets.CI_PRIVATE_KEY }}
     CI_DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
     CI_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
     CI_DEPLOY_USER: ${{ secrets.CI_DEPLOY_USER }}
     CI_DEPLOY_SSH_PORT: ${{ secrets.CI_DEPLOY_SSH_PORT }}
     CI_DEPLOY_SERVER: ${{ secrets.CI_DEPLOY_SERVER }}
     CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
    steps:
      - name: Check version
        uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.CI_PRIVATE_KEY }}  
      - name: Deploy to DigitalOcean
        run: |
          bash ./deploy/scripts/deploy_to_server.sh
          
  notification:
    runs-on: ubuntu-latest
    env:
      BUILD_FAIL: ${{ (needs.build.result == 'failure' || needs.build.result == 'timed_out') || (needs.deploy.result == 'failure' || needs.deploy.result == 'timed_out') }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    needs:
      - build
      - deploy
    if: ${{ always() || (needs.build.result == 'failure' || needs.build.result == 'timed_out') || (needs.deploy.result == 'failure' || needs.deploy.result == 'timed_out') }}
    steps:
      - name: Check version
        uses: actions/checkout@v4
      - name: Print var
        run: echo $BUILD_FAIL
      - name: List folder
        run: ls
      - name: Run deploy notification script
        run: |
          bash ./deploy/scripts/notification.sh
